### ISSUE TITLE
grunt watch never gets to the "delta" task if test(s) fail when initially run

### ISSUE THREAD

**Issue by tedyoung** [ngbp/ngbp#210]
If you have a failing Karma test when you first start `grunt watch`, it will never get to the `delta` section because the test will fail, causing the "watch" task to fail.

```
...
Running "index:build" (index) task

Running "karmaconfig:unit" (karmaconfig) task

Running "karma:continuous" (karma) task
WARN [config]: config.configure() is deprecated, please use config.set() instead.
INFO [karma]: Karma v0.10.8 server started at http://localhost:9018/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 31.0.1650 (Windows 7)]: Connected on socket qwjgmcWpBzvujro0e_gP
..
Chrome 31.0.1650 (Windows 7) for a suite configuration...
        Expected '2.0.0' to be '7.0.0'.
        Error: Expected '2.0.0' to be '7.0.0'.
            at c:/dev/backyard/src/app/suite-config.spec.js:15:35
            at Array.forEach (native)
            at null.<anonymous> (c:/dev/src/app/suite-config.spec.js:14:21)
Chrome 31.0.1650 (Windows 7): Executed 3 of 3 (1 FAILED) (0.214 secs / 0.031 secs)
Warning: Task "karma:continuous" failed. Use --force to continue.

Aborted due to warnings.
```

If you run `grunt watch` with no failing tests, then it'll get to the `delta` task and everything's fine.

**Comment by joshdmiller** [comment]
This is true, but I'm not sure there's any way to fix it. The watch cannot function without a completed build, so a build must be performed prior to starting the watch; but part of the build is, of course, running the unit tests, without which the build cannot complete. Ergo, passing unit tests are a _de facto_ requirement of starting up the watch.

I'm definitely open to suggestions here, but I don't see any way around this.

**Comment by jjcf89** [comment]
I noticed someone in a different issue (Pull request?) created a build_only command that didn't run the karma tests.  Could this be run as a step that needs to succeed and have a the karma test run next as a step that can fail?
