### ISSUE TITLE
grunt compile error

### ISSUE THREAD

**Issue by giulioprovasi** [ngbp/ngbp#389]
When I try to compile the project, I get the following error:

```
Running "concat:compile_js" (concat) task
[D] Task source: /var/www/public/acme.app/node_modules/grunt-contrib-concat/tasks/concat.js
Verifying property concat.compile_js exists in config...Warning: An error occurred while processing a template (Cannot read property 'type' of undefined). Use --force to continue.
TypeError: An error occurred while processing a template (Cannot read property 'type' of undefined).
  at eval (/lodash/template/source[11]:20:23)
  at Function.template (/var/www/public/acme.app/node_modules/grunt/node_modules/lodash/lodash.js:3879:14)
  at Object.template.process (/var/www/public/acme.app/node_modules/grunt/lib/grunt/template.js:75:27)
  at /var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:75:27
  at recurse (/var/www/public/acme.app/node_modules/grunt/node_modules/grunt-legacy-util/index.js:127:14)
  at Object.util.recurse (/var/www/public/acme.app/node_modules/grunt/node_modules/grunt-legacy-util/index.js:130:10)
  at Function.config.process (/var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:61:21)
  at Function.config.get (/var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:55:17)
  at /var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:69:23
  at recurse (/var/www/public/acme.app/node_modules/grunt/node_modules/grunt-legacy-util/index.js:127:14)
  at recurse (/var/www/public/acme.app/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
  at recurse (/var/www/public/acme.app/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
  at Object.util.recurse (/var/www/public/acme.app/node_modules/grunt/node_modules/grunt-legacy-util/index.js:130:10)
  at Function.config.process (/var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:61:21)
  at Function.config.get (/var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:55:17)
  at failProps (/var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:107:19)
  at Array.filter (native)
  at Object.config.requires [as requiresConfig] (/var/www/public/acme.app/node_modules/grunt/lib/grunt/config.js:106:40)
  at Object.<anonymous> (/var/www/public/acme.app/node_modules/grunt/lib/grunt/task.js:234:10)
  at Object.thisTask.fn (/var/www/public/acme.app/node_modules/grunt/lib/grunt/task.js:82:16)
  at Object.<anonymous> (/var/www/public/acme.app/node_modules/grunt/lib/util/task.js:301:30)
  at Task.runTaskFn (/var/www/public/acme.app/node_modules/grunt/lib/util/task.js:251:24)
  at Task.<anonymous> (/var/www/public/acme.app/node_modules/grunt/lib/util/task.js:300:12)
  at /var/www/public/acme.app/node_modules/grunt/lib/util/task.js:227:11
  at process._tickCallback (node.js:419:13)

```

Can someone help me ?

**Comment by giulioprovasi** [comment]
Of course, after searching everywhere and posting a question, I found the solution by changing my terms :+1: 
Duplicates of https://github.com/ngbp/ngbp/issues/344
