### ISSUE TITLE
Uglification failed

### ISSUE THREAD

**Issue by prassh123** [ngbp/ngbp#398]
{ message: 'Unexpected token: punc (.)',
  filename: 'bin/assets/ngbp-0.3.2.js',
  line: 50958,
  col: 0,
  pos: 1840357,
  stack: 'Error\n    at new JS_Parse_Error (/Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:680:9)\n    at token_error (/Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:688:9)\n    at unexpected (/Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:694:9)\n    at /Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:784:17\n    at /Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:727:24\n    at /Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1474:23\n    at Object.parse (/Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1484:7)\n    at /Users/praghavan/kaleidoscope/src/main/ui/node_modules/grunt-contrib-uglify/tasks/lib/uglify.js:39:27' }

> > Uglifying source "bin/assets/ngbp-0.3.2.js" failed.
> > Warning: Uglification failed.
> > Unexpected token: punc (.). 
> > Line 50958 in bin/assets/ngbp-0.3.2.js
> >  Use --force to continue.

**Comment by fcarribero** [comment]
Take a look if you are not including any CSS file into the vendor_files.js array in build.config.js

**Comment by balazsnemeth** [comment]
Do you have any update on this? Could you provide any info about how did you solve this issue?
